name: recognizer
description: RECOGNIZER.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  get: ^4.6.3
  # Package Info
  package_info_plus: ^4.1.0

  # Camera
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  # Path
  path: ^1.8.3
  path_provider: ^2.1.1

  # Machine Learning Text Recognition
  google_mlkit_text_recognition       : ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
