name: recognizer
description: RECOGNIZER.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  get: ^4.6.3
  # Package Info
  package_info_plus: ^4.1.0

  # Camera
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  # Path
  path: ^1.8.3
  path_provider: ^2.1.1

  # Machine Learning
  google_mlkit_barcode_scanning       : ^0.9.0
  google_mlkit_digital_ink_recognition: ^0.9.0
  google_mlkit_face_detection         : ^0.8.0
  google_mlkit_face_mesh_detection    : ^0.0.1
  google_mlkit_image_labeling         : ^0.9.0
  google_mlkit_object_detection       : ^0.10.0
  google_mlkit_pose_detection         : ^0.9.0
  google_mlkit_selfie_segmentation    : ^0.5.0
  google_mlkit_text_recognition       : ^0.10.0

  google_mlkit_entity_extraction      : ^0.10.0
  google_mlkit_language_id            : ^0.8.0
  google_mlkit_translation            : ^0.8.0
  google_mlkit_smart_reply            : ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
